import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ChatProvider } from "~/components/chat-interface";
import { CommandPalette } from "~/components/command-palette";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          {/* <InspectorStateProvider> */}
            <ChatProvider>{children}</ChatProvider>
          {/* </InspectorStateProvider> */}
        </TRPCReactProvider>
      </body>
    </html>
  );
}
